# Error Correction in Single Neuron

In [1]:
import numpy as np

In [75]:
class Neuron:
    def __init__(self, num_inputs):
        self.weights = np.random.rand(num_inputs)
        self.bias = np.random.rand()

    def activate(self, inputs):
        weighted_sum = np.dot(inputs, self.weights) + self.bias
        activation = self.sigmoid(weighted_sum)
        return activation

    def sigmoid(self, x):
        return 1/(1+np.exp(-x))

    def train(self, inputs, target, lr = 0.01):
        out = self.activate(inputs)
        error = target - out
        self.weights += lr*error*inputs
        self.bias += lr*error

In [66]:
neuron = Neuron(5)

In [71]:
for i in range(100000):
    neuron.train([-10, 10, 15, 12, -0.1], [0, 0, 1 ,1 ,0])

In [72]:
neuron.weights

array([ 90.87444568, -89.60966194,  73.45818003,  58.72798497,
         1.08270163])

In [73]:
output = neuron.activate([-10, 10, 15, 12, -0.1])

In [74]:
print(output)

[0.00129004 0.00129004 0.99929996 0.99929996 0.00129004]


# Memory Based Learning

In [1]:
import numpy as np
from collections import Counter

In [2]:
class Neuron:
    def __init__(self, k):
        self.k = k
        self.X_train = None
        self.y_train = None

    def train(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train

    def prediction(self, X_test):
        preds = [self.predict(x) for x in X_test]
        return np.array(preds)

    def predict(self, x):
        distances = [self.distance(x, x_train) for x_train in self.X_train]
        k_indices = np.argsort(distances)[:self.k]
        k_nearest_labels = [self.y_train[i] for i in k_indices]
        most_common = Counter(k_nearest_labels).most_common(1)
        return most_common[0][0]

    def distance(self, x1, x2):
        return np.sqrt(np.sum((x1-x2)**2))

In [3]:
neuron = Neuron(3)

In [4]:
X_train = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y_train = np.array([0, 0, 1, 1])

In [5]:
neuron.train(X_train, y_train)

In [7]:
preds = neuron.prediction([[2, 2], [1, 3], [2, 5]])

In [8]:
preds

array([0, 0, 1])